import React, { createContext, useContext, useState, useEffect } from 'react';
import { useAuth } from './AuthContext';
import { doc, getDoc } from 'firebase/firestore';
import { db } from '../firebase';

export type Language = 'bn' | 'en';

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

// Translations dictionary
const translations: Record<Language, Record<string, string>> = {
  bn: {
    'app.title': 'ডিজিটাল খামার প্রো',
    // Layout Tab Bar
    'menu.home': 'হোম',
    'menu.dashboard': 'ড্যাশবোর্ড',
    'menu.batches': 'ব্যাচ',
    'menu.feed': 'খাবার',
    'menu.medicine': 'ঔষধ',
    'menu.expenses': 'হিসাব',
    'menu.profile': 'প্রোফাইল',
    'menu.reports': 'রিপোর্ট',
    
    // Profile
    'profile.title': 'ব্যক্তিগত তথ্য',
    'profile.name': 'আপনার নাম',
    'profile.phone': 'মোবাইল নাম্বার',
    'profile.farmName': 'খামারের নাম',
    'profile.farmNamePlaceholder': 'খামারের নাম (ঐচ্ছিক)',
    'profile.appLanguage': 'অ্যাপের ভাষা',
    'profile.bengali': 'বাংলা',
    'profile.english': 'English',
    'profile.save': 'সেভ করুন',
    'profile.saving': 'সেভ হচ্ছে...',
    'profile.support': 'সাহায্য ও সাপোর্ট',
    'profile.supportWait': 'ডেভেলপারের সাথে যোগাযোগ করুন',
    'profile.about': 'অ্যাপ সম্পর্কে',
    'profile.aboutSub': 'ডেভেলপার এবং ভার্সন',
    'profile.logout': 'লগআউট',
    'profile.privacyPolicy': 'প্রাইভেসি পলিসি (Privacy Policy)',
    
    // Dashboard
    'dashboard.greeting': 'স্বাগতম,',
    'dashboard.khamari': 'খামারি',
    'dashboard.activeBatches': 'চলমান ব্যাচ',
    'dashboard.totalBirds': 'মোট সংখ্যা',
    'dashboard.totalMortality': 'মোট মৃত্যু',
    'dashboard.recentActivity': 'সাম্প্রতিক কার্যক্রম',
    'dashboard.noActivity': 'কোনো কার্যক্রম নেই',
    'dashboard.viewDetails': 'বিস্তারিত দেখুন',
    'dashboard.age': 'বয়স',
    'dashboard.days': 'দিন',
    'dashboard.quickActions': 'কুইক অ্যাকশন',
    'dashboard.feed': 'খাবার',
    'dashboard.medicine': 'ঔষধ এন্ট্রি',
    'dashboard.mortality': 'মৃত্যু এন্ট্রি',
    'dashboard.expenses': 'খরচ এন্ট্রি',
    'dashboard.sales': 'বিক্রয়',
    'dashboard.dues': 'বকেয়া',
    'dashboard.reports': 'রিপোর্টস',
    'dashboard.weight': 'ওজন',
    'dashboard.guidelines': 'পরামর্শ',
    'dashboard.noBatches': 'কোনো চলমান ব্যাচ নেই',
    'dashboard.noBatchesSub': 'শুরু করতে আপনার প্রথম ব্যাচ তৈরি করুন।',
    'dashboard.createBatch': 'নতুন ব্যাচ তৈরি করুন',

    // Common
    'common.addRecord': 'নতুন রেকর্ড',
    'common.save': 'সংরক্ষণ করুন',
    'common.saving': 'সংরক্ষণ হচ্ছে...',
    'common.cancel': 'বাতিল',
    'common.delete': 'মুছুন',
    'common.edit': 'সম্পাদনা',
    'common.deleting': 'মুছা হচ্ছে...',
    'common.success': 'সফল হয়েছে!',
    'common.error': 'সমস্যা হয়েছে',
    'common.confirmDelete': 'মুছে ফেলার নিশ্চিতকরণ',
    'common.confirmDeleteMsg': 'আপনি কি নিশ্চিত যে আপনি এটি মুছে ফেলতে চান?',
    'common.yes': 'হ্যাঁ, মুছুন',
    'common.no': 'না, বাতিল',
    'common.date': 'তারিখ',
    'common.details': 'বিস্তারিত (ঐচ্ছিক)',
    'common.noData': 'কোনো তথ্য পাওয়া যায়নি',
    'common.selectBatch': 'প্রথমে একটি ব্যাচ নির্বাচন করুন',
    'common.totalAmount': 'মোট টাকা',
    'common.paidAmount': 'জমা/পরিশোধ',
    'common.personName': 'ব্যক্তির নাম',
    'common.batchName': 'ব্যাচের নাম (যেমন: ব্যাচ-১)',
    'common.loading': 'লোড হচ্ছে...',

    // Batches
    'batches.title': 'ব্যাচ ম্যানেজমেন্ট',
    'batches.addBatch': 'নতুন ব্যাচ যোগ করুন',
    'batches.batchNameLabel': 'ব্যাচের নাম',
    'batches.batchNamePlaceholder': 'যেমন: ব্যাচ ১',
    'batches.farmType': 'খামারের ধরন',
    'batches.poultry': 'মুরগি / হাঁস / পাখি',
    'batches.cattle': 'গরু / ছাগল / মহিষ',
    'batches.fish': 'মাছ',
    'batches.totalChicks': 'মোট সংখ্যা',
    'batches.costPerChick': 'প্রতিটির ক্রয়মূল্য (৳)',
    'batches.status': 'বর্তমান অবস্থা',
    'batches.active': 'চলমান',
    'batches.completed': 'সম্পন্ন',
    'batches.markComplete': 'ব্যাচ শেষ করুন',
    'batches.startDate': 'শুরুর তারিখ',
    'batches.batchDetails': 'ব্যাচের বিবরণ',
    'batches.chicksCount': 'বাচ্চার সংখ্যা',
    'batches.totalCost': 'মোট খরচ:',
    'batches.totalSales': 'মোট বিক্রয়:',
    'batches.profit': 'লাভ (Profit)',
    'batches.loss': 'ক্ষতি (Loss)',
    'batches.net': 'নীট ',
    'batches.noBatches': 'কোনো ব্যাচ পাওয়া যায়নি। নতুন ব্যাচ যোগ করুন।',
    'batches.confirmCompleteTitle': 'ব্যাচ শেষ করার নিশ্চিতকরণ',
    'batches.confirmCompleteMsg': 'আপনি কি নিশ্চিত যে এই ব্যাচটি সম্পন্ন করতে চান?',
    'batches.started': 'শুরু:',
    'batches.chicksItem': 'টি',
    'batches.currencyPerItem': '(প্রতিটি)',
    'batches.calculating': 'হিসাব লোড হচ্ছে...',
    'batches.addSuccess': 'নতুন ব্যাচ যোগ করা হয়েছে!',
    'batches.addError': 'ব্যাচ যোগ করতে সমস্যা হয়েছে।',
    'batches.completeSuccess': 'ব্যাচ সম্পন্ন হয়েছে।',
    'batches.updateError': 'আপডেট করতে সমস্যা হয়েছে।',
    'batches.delSuccess': 'ব্যাচ মুছে ফেলা হয়েছে!',
    'batches.delError': 'মুছে ফেলতে সমস্যা হয়েছে।',

    // Feed
    'feed.title': 'খাবার ব্যবস্থাপনা',
    'feed.addFeed': 'নতুন খাবার রেকর্ড',
    'feed.selectBatch': 'ব্যাচ নির্বাচন করুন',
    'feed.selectOption': 'নির্বাচন করুন...',
    'feed.date': 'তারিখ',
    'feed.feedType': 'খাবারের ধরন',
    'feed.starter': 'Starter / প্রাথমিক',
    'feed.grower': 'Grower / মাঝারি বয়সের',
    'feed.finisher': 'Finisher / শেষ বয়সের',
    'feed.cattleOption': 'দানা/ভুষি (Cattle/Goat)',
    'feed.grass': 'কাঁচা ঘাস (Grass)',
    'feed.hay': 'খড় (Hay)',
    'feed.silage': 'সাইলেজ (Silage)',
    'feed.fishFloat': 'ভাসমান খাবার (Fish)',
    'feed.fishSink': 'ডুবন্ত খাবার (Fish)',
    'feed.khoil': 'খৈল/কুড়া',
    'feed.other': 'অন্যান্য',
    'feed.quantityBags': 'পরিমাণ (ব্যাগ/বস্তা/কেজি)',
    'feed.pricePerUnit': 'প্রতি একক দাম (৳)',
    'feed.totalPrice': 'মোট দাম:',
    'feed.shopName': 'দোকানের নাম / প্রাপক',
    'feed.shopPlaceholder': 'কোথা থেকে কেনা?',
    'feed.mobileNum': 'মোবাইল নম্বর',
    'feed.paidAmt': 'জমা/পরিশোধ (৳)',
    'feed.defaultAmt': 'ডিফল্ট: ৳ ',
    'feed.dueMsg': 'বাকি: ৳ ',
    'feed.dueMsgAuto': ' (স্বয়ংক্রিয়ভাবে বকেয়া খাতায় যোগ হবে)',
    'feed.returnMsg': 'ফেরত পাবেন: ৳ ',
    'feed.batchSelectionReq': 'ব্যাচ নির্বাচন করুন',
    'feed.dueNameReq': 'বাকি থাকলে যাকে দিবেন তার নাম লিখতে হবে!',
    'feed.feedFood': ' এর {type} খাবার: ',
    'feed.addSuccess': 'খাবারের হিসাব যোগ করা হয়েছে!',
    'feed.addError': 'যোগ করতে সমস্যা হয়েছে।',
    'feed.amountLabel': ' পরিমাণ ',
    'feed.perUnitLabel': ' /একক',
    'feed.shopLabel': 'দোকান: ',
    'feed.dueLabel': 'বাকি: ৳ ',
    'feed.paidLabel': 'পরিশোধিত',
    'feed.noRecords': 'কোনো হিসাব পাওয়া যায়নি।',
    
    // Medicine
    'medicine.title': 'ঔষধ এবং ভ্যাকসিন',
    'medicine.addMedicine': 'নতুন রেকর্ড',
    'medicine.batchLabel': 'ব্যাচ',
    'medicine.dateLabel': 'তারিখ',
    'medicine.typeLabel': 'ধরন',
    'medicine.optMedicine': 'ঔষধ (Medicine)',
    'medicine.optVaccine': 'ভ্যাকসিন (Vaccine)',
    'medicine.nameDescLabel': 'নাম/বিবরণ',
    'medicine.nameDescPlaceholder': 'ঔষধ বা ভ্যাকসিনের নাম',
    'medicine.shopLabel': 'দোকানের নাম / প্রাপক',
    'medicine.shopPlaceholder': 'কোথা থেকে কেনা?',
    'medicine.mobileLabel': 'মোবাইল নম্বর',
    'medicine.mobilePlaceholder': '017xxxxxxxx',
    'medicine.totalPrice': 'মোট দাম (৳)',
    'medicine.totalPricePlaceholder': 'সর্বমোট দাম',
    'medicine.paidAmt': 'জমা/পরিশোধ (৳)',
    'medicine.detailsNote': 'বিবরণ/নোট (ঐচ্ছিক)',
    'medicine.detailsPlaceholder': 'কী রোগের জন্য?',
    'medicine.vaccine': 'ভ্যাকসিন',
    'medicine.medicine': 'ঔষধ',
    'medicine.shopTxt': 'দোকান: ',
    'medicine.addSuccess': 'রেকর্ড যোগ করা হয়েছে!',
    'medicine.saveBtn': 'সংরক্ষণ করুন',
    'medicine.savingBtn': 'সংরক্ষণ হচ্ছে...',
    'medicine.recordVal': ' এর {type}: {name} {details}',

    // Expenses
    'expenses.title': 'অন্যান্য হিসাব',
    'expenses.addExpense': 'নতুন খরচ',
    'expenses.category': 'খরচের খাত',
    'expenses.amount': 'পরিমাণ (৳)',
    'expenses.optElectricity': 'বিদ্যুৎ বিল',
    'expenses.optLabor': 'শ্রমিক বা লেবার',
    'expenses.optTransport': 'গাড়ি ভাড়া বা যাতায়াত',
    'expenses.optDoctor': 'ডাক্তার ভিজিট',
    'expenses.optOther': 'অন্যান্য (বিবরণে লিখুন)',
    'expenses.categoryLabel': 'খাত',
    'expenses.receiverLabel': 'প্রাপক / যাকে দিচ্ছেন',
    'expenses.receiverPlaceholder': 'কার কাছে টাকা দিচ্ছেন?',
    'expenses.detailsPlaceholder': 'কীসের খরচ?',
    'expenses.missingReceiver': 'বাকি থাকলে প্রাপকের (যাকে দিবেন) নাম লিখতে হবে!',
    'expenses.addSuccess': 'খরচ যোগ করা হয়েছে!',
    'expenses.expenseDetails': ' এর {category} খরচ: ',

    // Sales
    'sales.title': 'বিক্রির হিসাব',
    'sales.addSale': 'নতুন বিক্রি',
    'sales.categoryLabel': 'পণ্যের ধরন / ক্যাটাগরি',
    'sales.catChicken': '🐔 ব্রয়লার / সোনালী মুরগি',
    'sales.catEgg': '🥚 ডিম (Eggs)',
    'sales.catMilk': '🥛 দুধ (Milk)',
    'sales.catManure': '💩 লিটার / সার (Manure)',
    'sales.catChicks': '🐣 বাচ্চা / ছানা (Chicks)',
    'sales.catCattle': '🐂 গরু / বাছুর (Cattle)',
    'sales.catFish': '🐟 মাছ (Fish)',
    'sales.catOther': '✨ অন্যান্য পণ্য (Custom)',
    'sales.eggUnitHali': 'হালি (৪ পিস)',
    'sales.eggUnitPcs': 'পিস (১টি)',
    'sales.eggUnitCase': 'কেস / পেটি (৩০টি)',
    'sales.milkUnitLiter': 'লিটার',
    'sales.manureUnitBag': 'বস্তা / ব্যাগ',
    'sales.manureUnitTrolley': 'ট্রলি / গাড়ি',
    'sales.productName': 'পণ্যের নাম / বিবরণ',
    'sales.productNamePlaceholder': 'যেমন: দেশি লাল ডিম, দেশি মুরগি ইত্যাদি',
    'sales.unitSelect': 'পরিমাপের একক',
    'sales.weight': 'মোট ওজন (কেজি)',
    'sales.pricePerKg': 'প্রতি কেজির দাম (৳)',
    'sales.numberOfChickens': 'মুরগির সংখ্যা (ঐচ্ছিক)',
    'sales.saleTypeLabel': 'বিক্রয়ের ধরন',
    'sales.typeWeight': 'ওজন অনুযায়ী (কেজি)',
    'sales.typeQuantity': 'সংখ্যা / একক অনুযায়ী',
    'sales.buyerName': 'ক্রেতার নাম',
    'sales.buyerNamePlaceholder': 'ক্রেতার নাম (যেমন: করিম ব্যাপারী)',
    'sales.buyerPhone': 'ক্রেতার মোবাইল নম্বর',
    'sales.buyerPhonePlaceholder': '017xxxxxxxx',
    'sales.totalWeight': 'মোট ওজন (কেজি)',
    'sales.weightPlaceholder': 'ওজন',
    'sales.quantityCount': 'পরিমাণ / সংখ্যা',
    'sales.qtyPlaceholder': 'পরিমাণ',
    'sales.qtyOptional': 'সংখ্যা (টি) [ঐচ্ছিক]',
    'sales.qtySoldPlaceholder': 'কতগুলো বিক্রি হলো?',
    'sales.pricePerKgLabel': 'প্রতি কেজি দর (৳)',
    'sales.pricePerKgPlaceholder': 'দর',
    'sales.pricePerPieceLabel': 'প্রতি এককের দাম (৳)',
    'sales.pricePerPiecePlaceholder': 'প্রতি এককের দাম',
    'sales.totalMoney': 'মোট টাকা:',
    'sales.cashReceived': 'জমা/নগদ পেয়েছি (৳)',
    'sales.cashPlaceholder': 'ডিফল্ট: ৳ ',
    'sales.returnToBuyer': 'ক্রেতা ফেরত পাবে: ৳ ',
    'sales.missingReceiver': 'বাকি থাকলে ক্রেতার নাম লিখতে হবে!',
    'sales.saleDetails': ' এর বিক্রয়',
    'sales.addSuccess': 'বিক্রয়ের হিসাব যোগ করা হয়েছে!',
    'sales.batchTxt': 'ব্যাচ: ',
    'sales.buyerTxt': ' | ক্রেতা: ',
    'sales.weightTxt': 'ওজন: ',
    'sales.kgTxt': ' কেজি',
    'sales.qtyTxt': 'সংখ্যা: ',
    'sales.pcsTxt': ' টি',
    'sales.rateTxt': 'দর: ৳ ',
    'sales.perKgTxt': '/কেজি',
    'sales.pieceRateTxt': 'প্রতিটির দর: ৳ ',

    // Mortality
    'mortality.title': 'মৃত্যু এন্ট্রি',
    'mortality.addRecord': 'নতুন রেকর্ড',
    'mortality.count': 'মৃতের সংখ্যা',
    'mortality.causeLabel': 'কারণ',
    'mortality.causePlaceholder': 'কারণ',
    'mortality.causeUnknown': 'অজ্ঞাত',
    'mortality.causeTxt': 'কারণ: ',
    'mortality.qtyLabel': ' টি',
    'mortality.addSuccess': 'মৃত্যু এন্ট্রি যোগ করা হয়েছে!',

    // Weight
    'weight.title': 'ওজন পরিমাপ',
    'weight.addRecord': 'নতুন পরিমাপ',
    'weight.ageDays': 'বয়স (দিন)',
    'weight.avgWeight': 'গড় ওজন (গ্রাম)',
    'weight.birdsSampled': 'কতটি পাখির ওজন মেপেছেন?',
    'weight.addSuccess': 'ওজন রেকর্ড যোগ করা হয়েছে!',

    // Dues
    'dues.title': 'বকেয়া/পাওনা',
    'dues.addRecord': 'নতুন হিসাব',
    'dues.type': 'কিসের হিসাব?',
    'dues.payable': 'দোকানের বাকি (আমি দেব)',
    'dues.receivable': 'ক্রেতার বাকি (আমি পাবো)',
    'dues.updateSuccess': 'জমা আপডেট করা হয়েছে!',
    'dues.updateReturn': 'জমা আপডেট হয়েছে! ফেরত দিন: ৳ ',
    'dues.markPaidSuccess': 'পরিশোধিত হিসাবে মার্ক করা হয়েছে।',
    'dues.whatRecord': 'কিসের হিসাব?',
    'dues.personLabel': 'নাম (দোকান/কোম্পানি/ব্যক্তি)',
    'dues.personPlaceholder': 'নাম',
    'dues.amountLabel': 'টাকার পরিমাণ (৳)',
    'dues.amountPlaceholder': 'পরিমাণ',
    'dues.detailsLabel': 'বিবরণ',
    'dues.detailsPlaceholder': 'কীসের টাকা? (যেমন: খাবার, ঔষধ বা প্রাণী ক্রয়)',
    'dues.summaryTitle': 'এক নজরে সবার মোট বকেয়া হিসাব',
    'dues.recordCount': 'টি রেকর্ড',
    'dues.totalReceivable': 'মোট পাবো: ৳ ',
    'dues.totalPayable': 'মোট দেব: ৳ ',
    'dues.allTransactions': 'সব লেনদেন ও হিসাবের বিস্তারিত',
    'dues.statusPaid': 'পরিশোধিত',
    'dues.statusPending': 'বকেয়া',
    'dues.markPaidBtn': 'পুরোপুরি শোধ',
    'dues.addDepositBtn': 'জমা দিন',
    'dues.historyTitle': 'জমা দেওয়ার হিস্ট্রি',
    'dues.totalSettle': 'মোট জমা:',
    'dues.remainingDue': 'বাকি আছে:',
    'dues.dueEmpty': 'বকেয়ার কোনো হিসাব নেই।',
    'dues.payDate': 'জমা দেওয়ার তারিখ',
    'dues.payAmount': 'টাকার পরিমাণ',
    'dues.cancelBtn': 'বাতিল করুন',
    'dues.verifyPayMsg': 'আপনি কি নিশ্চিত যে সম্পূর্ণ টাকা পরিশোধ করা হয়েছে?',

    // Reports
    'reports.title': 'রিপোর্ট ও বিশ্লেষণ',
    'reports.selectBatch': 'রিপোর্টের জন্য ব্যাচ নির্বাচন করুন',
    'reports.fcr': 'খাদ্য রূপান্তর হার (FCR)',
    'reports.netProfit': 'নিট লাভ',
    'reports.netLoss': 'নিট লোকসান',
    'reports.totalIncome': 'মোট আয় (বিক্রয়)',
    'reports.grandTotalCost': 'সর্বমোট খরচ (ক্রয়সহ)',
    'reports.breakdown': 'খরচের বিবরণী',
    'reports.incomeBreakdown': 'আয়ের বিবরণী (বিক্রয়)',
    'reports.expenseBreakdown': 'খরচের বিবরণী (ব্যয়)',
    'reports.costBuy': 'বাচ্চা/পশু ক্রয় মূল্য',
    'reports.costFeed': 'খাবারের খরচ',
    'reports.costMedicine': 'ওষুধ ও ভ্যাকসিনের খরচ',
    'reports.costOther': 'অন্যান্য পরিচালন খরচ',
    'reports.incomeChicken': 'মুরগি / পাখি বিক্রয়',
    'reports.incomeEgg': 'ডিম বিক্রয়',
    'reports.incomeMilk': 'দুধ বিক্রয়',
    'reports.incomeManure': 'সার / লিটার বিক্রয়',
    'reports.incomeCattle': 'গরু / পশু বিক্রয়',
    'reports.incomeFish': 'মাছ বিক্রয়',
    'reports.incomeChicks': 'বাচ্চা / ছানা বিক্রয়',
    'reports.incomeOther': 'অন্যান্য বিক্রয় ও আয়',
    'reports.noSalesYet': 'এখনও কোনো বিক্রয়ের হিসাব যুক্ত করা হয়নি।',
    'reports.noExpensesYet': 'এখনও কোনো খরচের হিসাব যুক্ত করা হয়নি।',
    'reports.viewItemized': 'বিস্তারিত ট্রানজেকশন তালিকা',
    'reports.hideItemized': 'তালিকা বন্ধ করুন',
    'reports.profitMargin': 'লাভের অনুপাত',
    'reports.roi': 'বিনিয়োগের লাভ (ROI)',
    'reports.tabSummary': 'সারসংক্ষেপ',
    'reports.tabIncome': 'আয়ের বিবরণী',
    'reports.tabExpense': 'খরচের বিবরণী',
    'reports.healthSummary': 'স্বাস্থ্য ও মৃত্যুহার',
    'reports.totalMortality': 'মোট মৃত্যু',
    'reports.mortalityRate': 'মৃত্যু হার',
    'reports.exportTitle': 'রিপোর্ট ডাউনলোড',
    'reports.pdfStarted': 'PDF ডাউনলোড শুরু হয়েছে',
    'reports.csvStarted': 'CSV ডাউনলোড শুরু হয়েছে',
    // Guidelines
    'guidelines.title': 'খামার পরামর্শ',
    'guidelines.subtitle': 'বিশেষজ্ঞ এবং স্পনসরদের সুপারিশ',
    'guidelines.farmType': 'খামারের ধরন নির্বাচন করুন',
    'guidelines.poultry': 'পোল্ট্রি (ব্রয়লার/সোনালী)',
    'guidelines.dairy': 'খামারের গরু (ডেইরি/ফ্যাটেনিং)',
    'guidelines.goat': 'ছাগল/ভেড়া',
    'guidelines.sponsorTitle': 'স্পনসর কোম্পানির বিশেষ পরামর্শ',
    'guidelines.sponsorDesc': 'এই কোম্পানির খাদ্য ও ঔষধ ব্যবহারে আপনি দ্রুত বৃদ্ধি এবং বেশি লাভ পাবেন।',
    'guidelines.profitHeadline': 'কেন এটি আপনার জন্য লাভজনক?',
    'guidelines.profitPoint1': 'খাদ্য রূপান্তর হার (FCR) অনেক ভালো, তাই কম খাবারে বেশি বৃদ্ধি।',
    'guidelines.profitPoint2': 'রোগ প্রতিরোধ ক্ষমতা বাড়ে, তাই মৃত্যুর হার কমে।',
    'guidelines.profitPoint3': 'বাজারে বিক্রির ওজন ১০-১৫ দিন আগেই চলে আসে, ফলে খরচ বাঁচে।',
    'guidelines.routineTitle': 'বয়স অনুযায়ী খাদ্য ও ঔষধের রুটিন',
    'guidelines.ageDays': 'বয়স: ',
    'guidelines.feedInfo': 'খাবার:',
    'guidelines.medicineInfo': 'ঔষধ:',
    
  },
  en: {
    'app.title': 'Digital Khamar Pro',
    // Layout Tab Bar
    'menu.home': 'Home',
    'menu.dashboard': 'Dashboard',
    'menu.batches': 'Batches',
    'menu.feed': 'Feed',
    'menu.medicine': 'Medicine',
    'menu.expenses': 'Accounts',
    'menu.profile': 'Profile',
    'menu.reports': 'Reports',

    // Profile
    'profile.title': 'Personal Information',
    'profile.name': 'Your Name',
    'profile.phone': 'Phone Number',
    'profile.farmName': 'Farm Name',
    'profile.farmNamePlaceholder': 'Farm Name (Optional)',
    'profile.appLanguage': 'App Language',
    'profile.bengali': 'বাংলা',
    'profile.english': 'English',
    'profile.save': 'Save Changes',
    'profile.saving': 'Saving...',
    'profile.support': 'Help & Support',
    'profile.supportWait': 'Contact Developer',
    'profile.about': 'About App',
    'profile.aboutSub': 'Developer & Version',
    'profile.logout': 'Logout',
    'profile.privacyPolicy': 'Privacy Policy',

    // Dashboard
    'dashboard.greeting': 'Welcome,',
    'dashboard.khamari': 'Farmer',
    'dashboard.activeBatches': 'Active Batches',
    'dashboard.totalBirds': 'Active Birds',
    'dashboard.totalMortality': 'Total Mortality',
    'dashboard.recentActivity': 'Recent Activity',
    'dashboard.noActivity': 'No recent activity',
    'dashboard.viewDetails': 'View Details',
    'dashboard.age': 'Age',
    'dashboard.days': 'days',
    'dashboard.quickActions': 'Quick Actions',
    'dashboard.feed': 'Feed',
    'dashboard.medicine': 'Medicine',
    'dashboard.mortality': 'Mortality',
    'dashboard.expenses': 'Expenses',
    'dashboard.sales': 'Sales',
    'dashboard.dues': 'Dues',
    'dashboard.reports': 'Reports',
    'dashboard.weight': 'Weight',
    'dashboard.guidelines': 'Guidelines',
    'dashboard.noBatches': 'No Active Batches',
    'dashboard.noBatchesSub': 'Create your first batch to get started.',
    'dashboard.createBatch': 'Create New Batch',

    // Common
    'common.addRecord': 'Add Record',
    'common.save': 'Save',
    'common.saving': 'Saving...',
    'common.cancel': 'Cancel',
    'common.delete': 'Delete',
    'common.edit': 'Edit',
    'common.deleting': 'Deleting...',
    'common.success': 'Success!',
    'common.error': 'An error occurred',
    'common.confirmDelete': 'Confirm Deletion',
    'common.confirmDeleteMsg': 'Are you sure you want to delete this?',
    'common.yes': 'Yes, Delete',
    'common.no': 'No, Cancel',
    'common.date': 'Date',
    'common.details': 'Details (Optional)',
    'common.noData': 'No data found',
    'common.selectBatch': 'Please select a batch first',
    'common.totalAmount': 'Total Amount',
    'common.paidAmount': 'Amount Paid',
    'common.personName': 'Person Name',
    'common.batchName': 'Batch Name (e.g., Batch-1)',
    'common.loading': 'Loading...',

    // Batches
    'batches.title': 'Batch Management',
    'batches.addBatch': 'Add New Batch',
    'batches.batchNameLabel': 'Batch Name',
    'batches.batchNamePlaceholder': 'e.g. Batch 1',
    'batches.farmType': 'Farm Type',
    'batches.poultry': 'Poultry / Duck / Bird',
    'batches.cattle': 'Cattle / Goat / Buffalo',
    'batches.fish': 'Fish',
    'batches.totalChicks': 'Total Count',
    'batches.costPerChick': 'Purchase Price',
    'batches.status': 'Status',
    'batches.active': 'Active',
    'batches.completed': 'Completed',
    'batches.markComplete': 'Mark as Complete',
    'batches.startDate': 'Start Date',
    'batches.batchDetails': 'Batch Details',
    'batches.chicksCount': 'Number of Count',
    'batches.totalCost': 'Total Cost:',
    'batches.totalSales': 'Total Sales:',
    'batches.profit': 'Profit',
    'batches.loss': 'Loss',
    'batches.net': 'Net ',
    'batches.noBatches': 'No batches found. Add a new batch.',
    'batches.confirmCompleteTitle': 'Confirm Completion',
    'batches.confirmCompleteMsg': 'Are you sure you want to mark this batch as complete?',
    'batches.started': 'Started:',
    'batches.chicksItem': 'items',
    'batches.currencyPerItem': '(per item)',
    'batches.calculating': 'Calculating...',
    'batches.addSuccess': 'New batch added successfully!',
    'batches.addError': 'Failed to add batch.',
    'batches.completeSuccess': 'Batch marked as completed.',
    'batches.updateError': 'Failed to update.',
    'batches.delSuccess': 'Batch deleted successfully!',
    'batches.delError': 'Failed to delete.',

    // Feed
    'feed.title': 'Feed Management',
    'feed.addFeed': 'Add Feed Record',
    'feed.selectBatch': 'Select Batch',
    'feed.selectOption': 'Select...',
    'feed.date': 'Date',
    'feed.feedType': 'Feed Type',
    'feed.starter': 'Starter',
    'feed.grower': 'Grower',
    'feed.finisher': 'Finisher',
    'feed.cattleOption': 'Grain/Bran (Cattle/Goat)',
    'feed.grass': 'Raw Grass',
    'feed.hay': 'Hay',
    'feed.silage': 'Silage',
    'feed.fishFloat': 'Floating Feed (Fish)',
    'feed.fishSink': 'Sinking Feed (Fish)',
    'feed.khoil': 'Oil Cake/Bran',
    'feed.other': 'Other',
    'feed.quantityBags': 'Quantity (Bags/Kg)',
    'feed.pricePerUnit': 'Price per unit/bag',
    'feed.totalPrice': 'Total Price:',
    'feed.shopName': 'Shop / Receiver Name',
    'feed.shopPlaceholder': 'Where was it bought?',
    'feed.mobileNum': 'Mobile Number',
    'feed.paidAmt': 'Amount Paid/Deposited',
    'feed.defaultAmt': 'Default: ',
    'feed.dueMsg': 'Due: ',
    'feed.dueMsgAuto': ' (Automatically added to dues logger)',
    'feed.returnMsg': 'You will get back: ',
    'feed.batchSelectionReq': 'Please select a batch',
    'feed.dueNameReq': 'Name is required if there is a due amount!',
    'feed.feedFood': ' feed: ',
    'feed.addSuccess': 'Feed record added successfully!',
    'feed.addError': 'Failed to add record.',
    'feed.amountLabel': ' qty ',
    'feed.perUnitLabel': ' /unit',
    'feed.shopLabel': 'Shop: ',
    'feed.dueLabel': 'Due: ',
    'feed.paidLabel': 'Paid',
    'feed.noRecords': 'No records found.',
    
    // Medicine
    'medicine.title': 'Medicine and Vaccines',
    'medicine.addMedicine': 'Add Record',
    'medicine.batchLabel': 'Batch',
    'medicine.dateLabel': 'Date',
    'medicine.typeLabel': 'Type',
    'medicine.optMedicine': 'Medicine',
    'medicine.optVaccine': 'Vaccine',
    'medicine.nameDescLabel': 'Name/Description',
    'medicine.nameDescPlaceholder': 'Name of medicine/vaccine',
    'medicine.shopLabel': 'Shop Name / Receiver',
    'medicine.shopPlaceholder': 'Where was it bought?',
    'medicine.mobileLabel': 'Mobile Number',
    'medicine.mobilePlaceholder': '017xxxxxxxx',
    'medicine.totalPrice': 'Total Price',
    'medicine.totalPricePlaceholder': 'Total Cost',
    'medicine.paidAmt': 'Amount Paid/Deposited',
    'medicine.detailsNote': 'Details/Note (Optional)',
    'medicine.detailsPlaceholder': 'For what disease?',
    'medicine.vaccine': 'Vaccine',
    'medicine.medicine': 'Medicine',
    'medicine.shopTxt': 'Shop: ',
    'medicine.addSuccess': 'Record added successfully!',
    'medicine.saveBtn': 'Save',
    'medicine.savingBtn': 'Saving...',
    'medicine.recordVal': ' {type}: {name} {details}',

    // Expenses
    'expenses.title': 'Other Expenses',
    'expenses.addExpense': 'Add Expense',
    'expenses.category': 'Category',
    'expenses.amount': 'Amount',
    'expenses.optElectricity': 'Electricity Bill',
    'expenses.optLabor': 'Labor/Worker',
    'expenses.optTransport': 'Transport/Fare',
    'expenses.optDoctor': 'Doctor Visit',
    'expenses.optOther': 'Other (Write below)',
    'expenses.categoryLabel': 'Category',
    'expenses.receiverLabel': 'Receiver Details',
    'expenses.receiverPlaceholder': 'Who takes the money?',
    'expenses.detailsPlaceholder': 'Expense details...',
    'expenses.missingReceiver': 'If there is a due amount, receiver name is required!',
    'expenses.addSuccess': 'Expense added successfully!',
    'expenses.expenseDetails': ' {category} expense: ',

    // Sales
    'sales.title': 'Sales Records',
    'sales.addSale': 'New Sale',
    'sales.categoryLabel': 'Product Category',
    'sales.catChicken': '🐔 Live Bird (Broiler / Sonali)',
    'sales.catEgg': '🥚 Eggs (ডিম)',
    'sales.catMilk': '🥛 Milk (দুধ)',
    'sales.catManure': '💩 Manure / Litter (সার)',
    'sales.catChicks': '🐣 Day-old Chicks (বাচ্চা)',
    'sales.catCattle': '🐂 Live Cattle / Calf (গরু)',
    'sales.catFish': '🐟 Live Fish (মাছ)',
    'sales.catOther': '✨ Other Products (অন্যান্য)',
    'sales.eggUnitHali': 'Hali (4 Pcs)',
    'sales.eggUnitPcs': 'Piece (1 Pc)',
    'sales.eggUnitCase': 'Case / Tray (30 Pcs)',
    'sales.milkUnitLiter': 'Liter',
    'sales.manureUnitBag': 'Bag / Sack',
    'sales.manureUnitTrolley': 'Trolley / Van',
    'sales.productName': 'Product Name / Detail',
    'sales.productNamePlaceholder': 'e.g., Red Farm Eggs, Layer Birds...',
    'sales.unitSelect': 'Measurement Unit',
    'sales.weight': 'Total Weight (kg)',
    'sales.pricePerKg': 'Price per Kg',
    'sales.numberOfChickens': 'Number of units (Optional)',
    'sales.saleTypeLabel': 'Sale Type',
    'sales.typeWeight': 'By Weight (kg)',
    'sales.typeQuantity': 'By Quantity / Units',
    'sales.buyerName': 'Buyer Name',
    'sales.buyerNamePlaceholder': 'Buyer Name (e.g. Karim Bepari)',
    'sales.buyerPhone': 'Buyer Mobile',
    'sales.buyerPhonePlaceholder': '017xxxxxxxx',
    'sales.totalWeight': 'Total Weight (kg)',
    'sales.weightPlaceholder': 'Weight',
    'sales.quantityCount': 'Quantity / Count',
    'sales.qtyPlaceholder': 'Quantity',
    'sales.qtyOptional': 'Quantity (pcs) [Optional]',
    'sales.qtySoldPlaceholder': 'How many sold?',
    'sales.pricePerKgLabel': 'Price per Kg (৳)',
    'sales.pricePerKgPlaceholder': 'Rate',
    'sales.pricePerPieceLabel': 'Price per Unit (৳)',
    'sales.pricePerPiecePlaceholder': 'Price per unit',
    'sales.totalMoney': 'Total Money:',
    'sales.cashReceived': 'Cash Received/Paid (৳)',
    'sales.cashPlaceholder': 'Default: ৳ ',
    'sales.returnToBuyer': 'Buyer will get returned: ৳ ',
    'sales.missingReceiver': 'If there is a due amount, buyer name is required!',
    'sales.saleDetails': ' sales',
    'sales.addSuccess': 'Sales calculation added!',
    'sales.batchTxt': 'Batch: ',
    'sales.buyerTxt': ' | Buyer: ',
    'sales.weightTxt': 'Weight: ',
    'sales.kgTxt': ' kg',
    'sales.qtyTxt': 'Qty: ',
    'sales.pcsTxt': ' pcs',
    'sales.rateTxt': 'Rate: ৳ ',
    'sales.perKgTxt': '/kg',
    'sales.pieceRateTxt': 'Price per piece: ৳ ',

    // Mortality
    'mortality.title': 'Mortality Records',
    'mortality.addRecord': 'Add Record',
    'mortality.count': 'Number of Deaths',
    'mortality.causeLabel': 'Cause',
    'mortality.causePlaceholder': 'Cause',
    'mortality.causeUnknown': 'Unknown',
    'mortality.causeTxt': 'Cause: ',
    'mortality.qtyLabel': ' qty',
    'mortality.addSuccess': 'Mortality entry added!',

    // Weight
    'weight.title': 'Weight Measurement',
    'weight.addRecord': 'Add Measure',
    'weight.ageDays': 'Age (Days)',
    'weight.avgWeight': 'Avg Weight (grams)',
    'weight.birdsSampled': 'How many birds were sampled?',
    'weight.addSuccess': 'Weight record added!',

    // Dues
    'dues.title': 'Dues and Payables',
    'dues.addRecord': 'Add Record',
    'dues.type': 'Type of Account',
    'dues.payable': 'I will pay (Payable)',
    'dues.receivable': 'I will receive (Receivable)',
    'dues.updateSuccess': 'Deposit updated!',
    'dues.updateReturn': 'Deposit updated! Return: ৳ ',
    'dues.markPaidSuccess': 'Marked as paid.',
    'dues.whatRecord': 'What is this regarding?',
    'dues.personLabel': 'Name (Shop/Company/Person)',
    'dues.personPlaceholder': 'Name',
    'dues.amountLabel': 'Amount (৳)',
    'dues.amountPlaceholder': 'Amount',
    'dues.detailsLabel': 'Details',
    'dues.detailsPlaceholder': 'What is the due for? (e.g., Feed, Medicine)',
    'dues.summaryTitle': 'Summary of all dues at a glance',
    'dues.recordCount': 'records',
    'dues.totalReceivable': 'Total Receivable: ৳ ',
    'dues.totalPayable': 'Total Payable: ৳ ',
    'dues.allTransactions': 'All Transactions Details',
    'dues.statusPaid': 'Fully Paid',
    'dues.statusPending': 'Pending',
    'dues.markPaidBtn': 'Mark Full Paid',
    'dues.addDepositBtn': 'Add Deposit',
    'dues.historyTitle': 'Payment History',
    'dues.totalSettle': 'Total Settled:',
    'dues.remainingDue': 'Remaining Due:',
    'dues.dueEmpty': 'No due records found.',
    'dues.payDate': 'Payment Date',
    'dues.payAmount': 'Taka Amount',
    'dues.cancelBtn': 'Cancel',
    'dues.verifyPayMsg': 'Are you sure you want to mark this complete amount as paid?',

    // Reports
    'reports.title': 'Reports & Analytics',
    'reports.selectBatch': 'Select Batch for Report',
    'reports.fcr': 'Feed Conversion Ratio (FCR)',
    'reports.netProfit': 'Net Profit',
    'reports.netLoss': 'Net Loss',
    'reports.totalIncome': 'Total Income (Sales)',
    'reports.grandTotalCost': 'Grand Total Cost (Inc. Purchase)',
    'reports.breakdown': 'Cost Breakdown',
    'reports.incomeBreakdown': 'Income Breakdown (Sales)',
    'reports.expenseBreakdown': 'Cost Breakdown (Expenses)',
    'reports.costBuy': 'Initial Purchase Cost',
    'reports.costFeed': 'Feed Cost',
    'reports.costMedicine': 'Medicine & Vaccines',
    'reports.costOther': 'Farm Management & Other',
    'reports.incomeChicken': 'Birds & Poultry Sales',
    'reports.incomeEgg': 'Egg Sales',
    'reports.incomeMilk': 'Milk Sales',
    'reports.incomeManure': 'Manure & Litter Sales',
    'reports.incomeCattle': 'Cattle & Livestock Sales',
    'reports.incomeFish': 'Fish Sales',
    'reports.incomeChicks': 'Chicks & Offspring Sales',
    'reports.incomeOther': 'Other Sales & Income',
    'reports.noSalesYet': 'No sales records added yet for this batch.',
    'reports.noExpensesYet': 'No expense records added yet for this batch.',
    'reports.viewItemized': 'View Itemized Transactions',
    'reports.hideItemized': 'Hide Transactions',
    'reports.profitMargin': 'Profit Margin',
    'reports.roi': 'Return on Investment (ROI)',
    'reports.tabSummary': 'Summary',
    'reports.tabIncome': 'Income Breakdown',
    'reports.tabExpense': 'Expense Breakdown',
    'reports.healthSummary': 'Health & Mortality',
    'reports.totalMortality': 'Total Mortality',
    'reports.mortalityRate': 'Mortality Rate',
    'reports.exportTitle': 'Export Report',
    'reports.pdfStarted': 'PDF download started',
    'reports.csvStarted': 'CSV download started',
    // Guidelines
    'guidelines.title': 'Farm Guidelines',
    'guidelines.subtitle': 'Expert and Sponsor Recommendations',
    'guidelines.farmType': 'Select Farm Type',
    'guidelines.poultry': 'Poultry (Broiler/Sonali)',
    'guidelines.dairy': 'Cattle (Dairy/Fattening)',
    'guidelines.goat': 'Goat/Sheep',
    'guidelines.sponsorTitle': 'Special Sponsor Advice',
    'guidelines.sponsorDesc': 'Using this company\'s feed and medicine will ensure faster growth and more profit.',
    'guidelines.profitHeadline': 'Why is it profitable for you?',
    'guidelines.profitPoint1': 'Better Feed Conversion Ratio (FCR), so more growth with less feed.',
    'guidelines.profitPoint2': 'Increases immunity, thus reducing mortality rate.',
    'guidelines.profitPoint3': 'Market selling weight is reached 10-15 days earlier, saving costs.',
    'guidelines.routineTitle': 'Age-based Feed & Medicine Routine',
    'guidelines.ageDays': 'Age: ',
    'guidelines.feedInfo': 'Feed:',
    'guidelines.medicineInfo': 'Medicine:',
    
  }
};

const LanguageContext = createContext<LanguageContextType>({
  language: 'bn',
  setLanguage: () => {},
  t: (key: string) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export const LanguageProvider: React.FC<{ children: React.ReactNode }> = ({ children }) => {
  const { currentUser, isDemoUser } = useAuth();
  
  // Try to get from local storage first for instant load
  const [language, setLanguageState] = useState<Language>(() => {
    const saved = localStorage.getItem('appLanguage');
    return (saved === 'en' || saved === 'bn') ? saved : 'bn';
  });

  // Then check Firestore user preferences (only for authenticated real users)
  useEffect(() => {
    const fetchUserLang = async () => {
      if (!currentUser || isDemoUser) return;
      try {
        const docRef = doc(db, 'users', currentUser.uid);
        const snap = await getDoc(docRef);
        if (snap.exists() && snap.data().language) {
          const userLang = snap.data().language;
          if (userLang === 'bn' || userLang === 'en') {
            setLanguageState(userLang as Language);
            localStorage.setItem('appLanguage', userLang);
          }
        }
      } catch (err) {
        console.warn('User language fetch warning:', err);
      }
    };
    fetchUserLang();
  }, [currentUser, isDemoUser]);

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('appLanguage', lang);
  };

  const t = (key: string): string => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
