import { DemoChickRate, initialChickRates } from './demoStore';

export interface MarketItem {
  id: string;
  nameBn: string;
  nameEn: string;
  category: 'poultry' | 'cattle' | 'fish';
  wholesale: string; // পাইকারি দর
  retail: string;    // খুচরা দর
  unitBn: string;
  unitEn: string;
  trend: 'up' | 'down' | 'steady';
  trendTextBn: string;
  trendTextEn: string;
}

export interface DivisionalMarketInfo {
  key: string;
  nameBn: string;
  nameEn: string;
  hubNoteBn: string;
  hubNoteEn: string;
  rates: MarketItem[];
  chickRates: DemoChickRate[];
}

export const NATIONAL_DEFAULT_MARKET_RATES: MarketItem[] = [
  // Poultry
  {
    id: 'broiler',
    nameBn: 'ব্রয়লার মুরগি (Broiler)',
    nameEn: 'Broiler Chicken',
    category: 'poultry',
    wholesale: '১৭৫ - ১৮০',
    retail: '১৯৫ - ২০৫',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'up',
    trendTextBn: '+২ ৳ বৃদ্ধি',
    trendTextEn: '+2 ৳ Up'
  },
  {
    id: 'sonali',
    nameBn: 'সোনালী মুরগি (Sonali)',
    nameEn: 'Sonali Chicken',
    category: 'poultry',
    wholesale: '২৮০ - ২৯০',
    retail: '৩০০ - ৩১৫',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'steady',
    trendTextBn: 'স্থিতিশীল',
    trendTextEn: 'Steady'
  },
  {
    id: 'deshi',
    nameBn: 'দেশি মুরগি (Deshi)',
    nameEn: 'Deshi Local Chicken',
    category: 'poultry',
    wholesale: '৪৬০ - ৪৮০',
    retail: '৫১০ - ৫৩০',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'up',
    trendTextBn: '+৫ ৳ বৃদ্ধি',
    trendTextEn: '+5 ৳ Up'
  },
  {
    id: 'chick_broiler',
    nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
    nameEn: 'Broiler DOC Chick',
    category: 'poultry',
    wholesale: '৫০ - ৫৪',
    retail: '৫৫ - ৫৮',
    unitBn: 'পিস',
    unitEn: 'Piece',
    trend: 'down',
    trendTextBn: '-১ ৳ হ্রাস',
    trendTextEn: '-1 ৳ Down'
  },
  {
    id: 'egg_layer',
    nameBn: 'লেয়ার লাল ডিম',
    nameEn: 'Layer Red Egg',
    category: 'poultry',
    wholesale: '৪৫ - ৪৭',
    retail: '৫০ - ৫২',
    unitBn: 'হালি',
    unitEn: '4 Pcs (Hali)',
    trend: 'steady',
    trendTextBn: 'স্থিতিশীল',
    trendTextEn: 'Steady'
  },

  // Cattle
  {
    id: 'beef_meat',
    nameBn: 'গরুর মাংস (Beef)',
    nameEn: 'Beef Meat',
    category: 'cattle',
    wholesale: '৭২০ - ৭৪০',
    retail: '৭৫০ - ৭৮০',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'steady',
    trendTextBn: 'স্থিতিশীল',
    trendTextEn: 'Steady'
  },
  {
    id: 'raw_milk',
    nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
    nameEn: 'Raw Fresh Milk',
    category: 'cattle',
    wholesale: '৬৫ - ৭০',
    retail: '৭৫ - ৮৫',
    unitBn: 'লিটার',
    unitEn: 'Litre',
    trend: 'up',
    trendTextBn: '+২ ৳ বৃদ্ধি',
    trendTextEn: '+2 ৳ Up'
  },
  {
    id: 'goat_meat',
    nameBn: 'খাসির মাংস (Mutton)',
    nameEn: 'Mutton / Goat Meat',
    category: 'cattle',
    wholesale: '১০০০ - ১০৫০',
    retail: '১১০০ - ১২০০',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'steady',
    trendTextBn: 'স্থিতিশীল',
    trendTextEn: 'Steady'
  },

  // Fish
  {
    id: 'fish_rui',
    nameBn: 'রুই / কাতলা মাছ',
    nameEn: 'Rui / Katla Fish',
    category: 'fish',
    wholesale: '২৭০ - ২৯০',
    retail: '৩২০ - ৩৫০',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'steady',
    trendTextBn: 'স্থিতিশীল',
    trendTextEn: 'Steady'
  },
  {
    id: 'fish_telapia',
    nameBn: 'তেলাপিয়া / পাঙ্গাস',
    nameEn: 'Tilapia / Pangas',
    category: 'fish',
    wholesale: '১৬০ - ১৭০',
    retail: '১৯০ - ২১০',
    unitBn: 'কেজি',
    unitEn: 'KG',
    trend: 'down',
    trendTextBn: '-৩ ৳ হ্রাস',
    trendTextEn: '-3 ৳ Down'
  }
];

// Helper to make custom chick rates for each division
const makeChickRates = (deltaA: number, deltaB: number, deltaC: number, trendOverride?: 'up' | 'down' | 'stable') => {
  return initialChickRates.map(chick => ({
    ...chick,
    gradeA: Math.max(5, chick.gradeA + deltaA),
    gradeB: Math.max(4, chick.gradeB + deltaB),
    gradeC: Math.max(3, chick.gradeC + deltaC),
    trend: trendOverride || chick.trend,
    updatedAt: new Date().toISOString()
  }));
};

export const DIVISION_MARKET_DATA: Record<string, DivisionalMarketInfo> = {
  national: {
    key: 'national',
    nameBn: 'জাতীয় গড় বাজার',
    nameEn: 'National Average',
    hubNoteBn: 'সমগ্র বাংলাদেশের প্রধান আড়ত ও মোকামের গড় দর',
    hubNoteEn: 'Average benchmark across all major markets in Bangladesh',
    rates: NATIONAL_DEFAULT_MARKET_RATES,
    chickRates: initialChickRates
  },
  dhaka: {
    key: 'dhaka',
    nameBn: 'ঢাকা বিভাগ',
    nameEn: 'Dhaka Division',
    hubNoteBn: 'গাজীপুর, সাভার, নরসিংদী, টাঙ্গাইল ও কাপ্তান বাজার আড়ত',
    hubNoteEn: 'Gazipur, Savar, Narsingdi, Tangail & Kaptan Bazar hubs',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৮০ - ১৮৫',
        retail: '২০০ - ২১০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৮৫ - ২৯৫',
        retail: '৩০৫ - ৩২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৭০ - ৪৯০',
        retail: '৫২০ - ৫৪০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৫ ৳ বৃদ্ধি',
        trendTextEn: '+5 ৳ Up'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৫২ - ৫৬',
        retail: '৫৭ - ৬২',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৬ - ৪৮',
        retail: '৫০ - ৫৩',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭৪০ - ৭৬০',
        retail: '৭৮০ - ৮০০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৭২ - ৭৮',
        retail: '৮০ - ৯০',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '১০৫০ - ১১০০',
        retail: '১১৫০ - ১২৫০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৮০ - ৩০০',
        retail: '৩৩০ - ৩৬০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৬৫ - ১৭৫',
        retail: '১৯৫ - ২২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      }
    ],
    chickRates: makeChickRates(2, 2, 2, 'up')
  },
  chattogram: {
    key: 'chattogram',
    nameBn: 'চট্টগ্রাম বিভাগ',
    nameEn: 'Chattogram Division',
    hubNoteBn: 'পাহাড়তলী, ফিরিঙ্গীবাজার ও ফেনী আড়ত',
    hubNoteEn: 'Pahartali, Firingibazar & Feni markets',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৮২ - ১৮৮',
        retail: '২০৫ - ২১৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৯০ - ৩০০',
        retail: '৩১০ - ৩২৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৪ ৳ বৃদ্ধি',
        trendTextEn: '+4 ৳ Up'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৮০ - ৫০০',
        retail: '৫৩০ - ৫৫০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৫৪ - ৫৮',
        retail: '৫৯ - ৬৪',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৮ - ৫০',
        retail: '৫২ - ৫৫',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭৫০ - ৭৭৫',
        retail: '৮০০ - ৮৩০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৭৫ - ৮২',
        retail: '৮৫ - ৯৫',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '১১০০ - ১১৫০',
        retail: '১২০০ - ১৩০০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৯০ - ৩১০',
        retail: '৩৪০ - ৩৮০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৭০ - ১৮০',
        retail: '২০০ - ২২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      }
    ],
    chickRates: makeChickRates(4, 3, 3, 'up')
  },
  rajshahi: {
    key: 'rajshahi',
    nameBn: 'রাজশাহী বিভাগ',
    nameEn: 'Rajshahi Division',
    hubNoteBn: 'বগুড়া, নাটোর, নওগাঁ ও জয়পুরহাট প্রধান পোল্ট্রি বেল্ট',
    hubNoteEn: 'Bogura, Natore, Naogaon & Joypurhat national production hub',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৭০ - ১৭৬',
        retail: '১৮৮ - ১৯৮',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৭৫ - ২৮৫',
        retail: '২৯৫ - ৩১০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৫০ - ৪৭০',
        retail: '৪৯০ - ৫১৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৪৮ - ৫২',
        retail: '৫৩ - ৫৭',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'down',
        trendTextBn: '-১ ৳ হ্রাস',
        trendTextEn: '-1 ৳ Down'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৪ - ৪৬',
        retail: '৪৮ - ৫০',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭০০ - ৭২৫',
        retail: '৭৩০ - ৭৬০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৫৫ - ৬২',
        retail: '৬৫ - ৭৫',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '৯৮০ - ১০২০',
        retail: '১০৫০ - ১১৪০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৫০ - ২৭০',
        retail: '২৯০ - ৩২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৫০ - ১৬০',
        retail: '১৭৫ - ১৯০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'down',
        trendTextBn: '-২ ৳ হ্রাস',
        trendTextEn: '-2 ৳ Down'
      }
    ],
    chickRates: makeChickRates(-3, -2, -2, 'down')
  },
  rangpur: {
    key: 'rangpur',
    nameBn: 'রংপুর বিভাগ',
    nameEn: 'Rangpur Division',
    hubNoteBn: 'দিনাজপুর, রংপুর, ঠাকুরগাঁও ও গাইবান্ধা মোকাম',
    hubNoteEn: 'Dinajpur, Rangpur, Thakurgaon & Gaibandha markets',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৭০ - ১৭৫',
        retail: '১৮৮ - ১৯৬',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৭০ - ২৮০',
        retail: '২৯০ - ৩০৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৪০ - ৪৬০',
        retail: '৪৮০ - ৫০৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৪৭ - ৫১',
        retail: '৫২ - ৫৬',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'down',
        trendTextBn: '-১ ৳ হ্রাস',
        trendTextEn: '-1 ৳ Down'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৩ - ৪৫',
        retail: '৪৭ - ৪৯',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৬৮০ - ৭১০',
        retail: '৭২০ - ৭৫০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৫০ - ৫৮',
        retail: '৬০ - ৭০',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '৯৫০ - ১০০০',
        retail: '১০২০ - ১১০০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৪০ - ২৬০',
        retail: '২৮০ - ৩১০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৪৫ - ১৫৫',
        retail: '১৭০ - ১৮৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'down',
        trendTextBn: '-৩ ৳ হ্রাস',
        trendTextEn: '-3 ৳ Down'
      }
    ],
    chickRates: makeChickRates(-4, -3, -3, 'down')
  },
  khulna: {
    key: 'khulna',
    nameBn: 'খুলনা বিভাগ',
    nameEn: 'Khulna Division',
    hubNoteBn: 'যশোর, চুকনগর, সাতক্ষীরা ও কুষ্টিয়া আড়ত',
    hubNoteEn: 'Jashore, Chuknagar, Satkhira & Kushtia markets',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৭৪ - ১৭৮',
        retail: '১৯২ - ২০০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৭৮ - ২৮৬',
        retail: '২৯৮ - ৩১২',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৫৫ - ৪৭৫',
        retail: '৫০০ - ৫২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৪৯ - ৫৩',
        retail: '৫৪ - ৫৮',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৫ - ৪৭',
        retail: '৪৯ - ৫১',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭১০ - ৭৩০',
        retail: '৭৪০ - ৭৭০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৬০ - ৬৫',
        retail: '৭০ - ৮০',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '৯৯০ - ১০৪০',
        retail: '১০৮০ - ১১৬০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৬০ - ২৮০',
        retail: '৩০০ - ৩৩০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৫৫ - ১৬৫',
        retail: '১৮০ - ১৯৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'down',
        trendTextBn: '-২ ৳ হ্রাস',
        trendTextEn: '-2 ৳ Down'
      }
    ],
    chickRates: makeChickRates(-1, -1, -1, 'stable')
  },
  mymensingh: {
    key: 'mymensingh',
    nameBn: 'ময়মনসিংহ বিভাগ',
    nameEn: 'Mymensingh Division',
    hubNoteBn: 'ভালুকা, ত্রিশাল, জামালপুর ও কিশোরগঞ্জ আড়ত',
    hubNoteEn: 'Bhaluka, Trishal, Jamalpur & Kishoreganj farm zone',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৭৫ - ১৮০',
        retail: '১৯৫ - ২০৪',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৮০ - ২৯০',
        retail: '৩০০ - ৩১৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৬০ - ৪৮০',
        retail: '৫১০ - ৫৩০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৪ ৳ বৃদ্ধি',
        trendTextEn: '+4 ৳ Up'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৫০ - ৫৪',
        retail: '৫৫ - ৫৯',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৪ - ৪৬',
        retail: '৪৮ - ৫০',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭১০ - ৭৩০',
        retail: '৭৫০ - ৭৮০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৬০ - ৬৬',
        retail: '৭০ - ৮০',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '১০০০ - ১০৫০',
        retail: '১১০০ - ১১৮০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৬০ - ২৭৫',
        retail: '২৯৫ - ৩২৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৫০ - ১৬০',
        retail: '১৭৫ - ১৯০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'down',
        trendTextBn: '-২ ৳ হ্রাস',
        trendTextEn: '-2 ৳ Down'
      }
    ],
    chickRates: makeChickRates(0, 0, 0, 'stable')
  },
  barishal: {
    key: 'barishal',
    nameBn: 'বরিশাল বিভাগ',
    nameEn: 'Barishal Division',
    hubNoteBn: 'বরিশাল নতুল্লাবাদ, পটুয়াখালী ও ভোলা মোকাম',
    hubNoteEn: 'Barishal Natullabad, Patuakhali & Bhola markets',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৮০ - ১৮৬',
        retail: '২০২ - ২১২',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৮৫ - ২৯৫',
        retail: '৩০৫ - ৩২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৭০ - ৪৯০',
        retail: '৫১৫ - ৫৩৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৫২ - ৫৬',
        retail: '৫৭ - ৬২',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'up',
        trendTextBn: '+১ ৳ বৃদ্ধি',
        trendTextEn: '+1 ৳ Up'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৬ - ৪৮',
        retail: '৫০ - ৫৩',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭৩০ - ৭৫০',
        retail: '৭৭০ - ৮০০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৭০ - ৭৬',
        retail: '৮০ - ৯০',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '১০৪০ - ১০৯০',
        retail: '১১৪০ - ১২২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৭০ - ২৯০',
        retail: '৩১০ - ৩৪০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৬০ - ১৭০',
        retail: '১৯০ - ২০৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'down',
        trendTextBn: '-২ ৳ হ্রাস',
        trendTextEn: '-2 ৳ Down'
      }
    ],
    chickRates: makeChickRates(2, 1, 1, 'up')
  },
  sylhet: {
    key: 'sylhet',
    nameBn: 'সিলেট বিভাগ',
    nameEn: 'Sylhet Division',
    hubNoteBn: 'কদমতলী, সুবহানীঘাট ও মৌলভীবাজার আড়ত',
    hubNoteEn: 'Kadamtali, Subhanighat & Moulvibazar hubs',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '১৮৫ - ১৯০',
        retail: '২০৬ - ২১৮',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '২৯২ - ৩০২',
        retail: '৩১২ - ৩২৮',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৪ ৳ বৃদ্ধি',
        trendTextEn: '+4 ৳ Up'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '৪৮৫ - ৫০৫',
        retail: '৫৩৫ - ৫৬০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'up',
        trendTextBn: '+৫ ৳ বৃদ্ধি',
        trendTextEn: '+5 ৳ Up'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '৫৪ - ৫৮',
        retail: '৫৯ - ৬৪',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '৪৮ - ৫০',
        retail: '৫২ - ৫৫',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'up',
        trendTextBn: '+২ ৳ বৃদ্ধি',
        trendTextEn: '+2 ৳ Up'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '৭৫০ - ৭৭৫',
        retail: '৭৯০ - ৮২৫',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '৭৫ - ৮০',
        retail: '৮৫ - ৯৫',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'up',
        trendTextBn: '+৩ ৳ বৃদ্ধি',
        trendTextEn: '+3 ৳ Up'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '১০৮০ - ১১৪০',
        retail: '১১৮০ - ১২৮০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '২৯০ - ৩১৫',
        retail: '৩৪০ - ৩৮০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '১৬৮ - ১৭৮',
        retail: '২০০ - ২২০',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      }
    ],
    chickRates: makeChickRates(3, 2, 2, 'up')
  },
  international: {
    key: 'international',
    nameBn: 'আন্তর্জাতিক / নিজস্ব বাজার',
    nameEn: 'International / Custom',
    hubNoteBn: 'প্রবাসী ও আন্তর্জাতিক খামারিদের স্থানীয় প্রচলিত দর',
    hubNoteEn: 'Expat & International farmers local market rates',
    rates: [
      {
        id: 'broiler',
        nameBn: 'ব্রয়লার মুরগি (Broiler)',
        nameEn: 'Broiler Chicken',
        category: 'poultry',
        wholesale: '180',
        retail: '205',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'sonali',
        nameBn: 'সোনালী মুরগি (Sonali)',
        nameEn: 'Sonali Chicken',
        category: 'poultry',
        wholesale: '280',
        retail: '310',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'deshi',
        nameBn: 'দেশি মুরগি (Deshi)',
        nameEn: 'Deshi Local Chicken',
        category: 'poultry',
        wholesale: '460',
        retail: '520',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'chick_broiler',
        nameBn: 'একদিন বাচ্চা (ব্রয়লার DOC)',
        nameEn: 'Broiler DOC Chick',
        category: 'poultry',
        wholesale: '50',
        retail: '56',
        unitBn: 'পিস',
        unitEn: 'Piece',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'egg_layer',
        nameBn: 'লেয়ার লাল ডিম',
        nameEn: 'Layer Red Egg',
        category: 'poultry',
        wholesale: '45',
        retail: '50',
        unitBn: 'হালি',
        unitEn: '4 Pcs (Hali)',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'beef_meat',
        nameBn: 'গরুর মাংস (Beef)',
        nameEn: 'Beef Meat',
        category: 'cattle',
        wholesale: '720',
        retail: '760',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'raw_milk',
        nameBn: 'খাঁটি তরল দুধ (Fresh Milk)',
        nameEn: 'Raw Fresh Milk',
        category: 'cattle',
        wholesale: '65',
        retail: '80',
        unitBn: 'লিটার',
        unitEn: 'Litre',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'goat_meat',
        nameBn: 'খাসির মাংস (Mutton)',
        nameEn: 'Mutton / Goat Meat',
        category: 'cattle',
        wholesale: '1000',
        retail: '1150',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_rui',
        nameBn: 'রুই / কাতলা মাছ',
        nameEn: 'Rui / Katla Fish',
        category: 'fish',
        wholesale: '280',
        retail: '330',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      },
      {
        id: 'fish_telapia',
        nameBn: 'তেলাপিয়া / পাঙ্গাস',
        nameEn: 'Tilapia / Pangas',
        category: 'fish',
        wholesale: '160',
        retail: '195',
        unitBn: 'কেজি',
        unitEn: 'KG',
        trend: 'steady',
        trendTextBn: 'স্থিতিশীল',
        trendTextEn: 'Steady'
      }
    ],
    chickRates: makeChickRates(0, 0, 0, 'stable')
  }
};

export const DIVISION_KEYS = [
  { key: 'national', nameBn: 'জাতীয় গড় বাজার', nameEn: 'National Avg' },
  { key: 'dhaka', nameBn: 'ঢাকা বিভাগ', nameEn: 'Dhaka' },
  { key: 'chattogram', nameBn: 'চট্টগ্রাম বিভাগ', nameEn: 'Chattogram' },
  { key: 'rajshahi', nameBn: 'রাজশাহী বিভাগ (বগুড়া)', nameEn: 'Rajshahi' },
  { key: 'rangpur', nameBn: 'রংপুর বিভাগ', nameEn: 'Rangpur' },
  { key: 'khulna', nameBn: 'খুলনা বিভাগ (যশোর)', nameEn: 'Khulna' },
  { key: 'mymensingh', nameBn: 'ময়মনসিংহ বিভাগ', nameEn: 'Mymensingh' },
  { key: 'barishal', nameBn: 'বরিশাল বিভাগ', nameEn: 'Barishal' },
  { key: 'sylhet', nameBn: 'সিলেট বিভাগ', nameEn: 'Sylhet' },
  { key: 'international', nameBn: 'আন্তর্জাতিক / নিজস্ব বাজার', nameEn: 'International / Custom' }
];

export function getDivisionData(key: string): DivisionalMarketInfo {
  return DIVISION_MARKET_DATA[key] || DIVISION_MARKET_DATA.national;
}
