// Sonali Poultry SOP & Growth Standard Data (1 to 60 Days)
// Grounded in Department of Livestock Services (DLS) Bangladesh & Commercial Sonali Management Guidelines

import { DailySopItem } from './broilerSopData';

export const SONALI_SOP_SCHEDULE: DailySopItem[] = [
  {
    day: 1,
    week: 1,
    feedDailyGm: 4,
    feedCumGm: 4,
    bodyWeightGm: 38,
    fcrStd: 0.25,
    tempFMin: 92,
    tempFMax: 95,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: [
      'Pre-heat brooding pen and prepare glucose/electrolyte water',
      'Provide Sonali starter crumble on paper trays (4g/chick)',
      'Crop fill audit at 4, 8, 12 hours (target >80%)'
    ],
    tasksBn: [
      'ব্রুডিং ঘর প্রি-হিট করুন ও গ্লুকোজ/ইলেক্ট্রোলাইট মিশ্রিত সুপেয় পানি প্রস্তুত রাখুন',
      'কাগজ বা ট্রেতে সোনালীর স্টার্টার ক্রাম্বল ফিড ছিটিয়ে দিন (বাচ্চাপ্রতি ৪ গ্রাম)',
      '৪, ৮ ও ১২ ঘণ্টায় ক্রপ বা পেটে খাবার পরীক্ষা করুন (৮০% বাচ্চার পেট ভরা থাকতে হবে)'
    ],
    isCritical: true
  },
  {
    day: 2,
    week: 1,
    feedDailyGm: 5,
    feedCumGm: 9,
    bodyWeightGm: 42,
    fcrStd: 0.35,
    tempFMin: 90,
    tempFMax: 93,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Crop fill audit at 48 hours (100% target)', 'Maintain 92-93°F uniform warmth'],
    tasksBn: ['৪৮ ঘণ্টায় ক্রপ পরীক্ষা করুন (১০০% বাচ্চার পেট নরম খাবারে ভরা থাকবে)', 'ব্রুডারে ৯২-৯৩°F তাপমাত্রা বজায় রাখুন']
  },
  {
    day: 3,
    week: 1,
    feedDailyGm: 6,
    feedCumGm: 15,
    bodyWeightGm: 47,
    fcrStd: 0.45,
    tempFMin: 90,
    tempFMax: 92,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Remove droppings from paper', 'Add small feeder trays gradually'],
    tasksBn: ['কাগজের ওপর জমা মল পরিষ্কার করুন', 'ধীরে ধীরে ছোট ফিডিং ট্রের ব্যবহার শুরু করুন']
  },
  {
    day: 4,
    week: 1,
    feedDailyGm: 7,
    feedCumGm: 22,
    bodyWeightGm: 52,
    fcrStd: 0.52,
    tempFMin: 89,
    tempFMax: 91,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Replenish water 3 times a day', 'Inspect chick activity and spreading pattern'],
    tasksBn: ['দিনে অন্তত ৩ বার সুপেয় পানি পরিবর্তন করুন', 'বাচ্চার ওমের নিচে ছড়ানোর ধরন খেয়াল করুন']
  },
  {
    day: 5,
    week: 1,
    feedDailyGm: 8,
    feedCumGm: 30,
    bodyWeightGm: 57,
    fcrStd: 0.60,
    tempFMin: 88,
    tempFMax: 90,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Check litter moisture under drinkers', 'Prepare for Day 6-7 BCRDV (Ranikhet) eye drop vaccination'],
    tasksBn: ['পানির পাত্রের নিচের লিটার শুকনা রাখুন', '৬-৭ দিনে বিসিআরডিভি (রাণীক্ষেত) চোখের ড্রপ ভ্যাকসিনের প্রস্তুতি নিন']
  },
  {
    day: 6,
    week: 1,
    feedDailyGm: 9,
    feedCumGm: 39,
    bodyWeightGm: 62,
    fcrStd: 0.68,
    tempFMin: 88,
    tempFMax: 90,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['BCRDV eye drop vaccination in the morning or evening', 'Add Vitamin-C in water as anti-stress'],
    tasksBn: ['সকাল বা সন্ধ্যায় বিসিআরডিভি (রাণীক্ষেত) ১ ফোঁটা চোখে ড্রপ দিন', 'টিকার পর ধকল কমাতে পানিতে ভিটামিন সি দিন'],
    isCritical: true
  },
  {
    day: 7,
    week: 1,
    feedDailyGm: 10,
    feedCumGm: 49,
    bodyWeightGm: 67,
    fcrStd: 0.73,
    tempFMin: 87,
    tempFMax: 89,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['7-Day sample weight check (target 65-70g)', 'Gradually reduce temperature by 5°F each week'],
    tasksBn: ['৭ম দিনের স্যাম্পল ওজন নিন (টার্গেট ৬৫-৭০ গ্রাম)', 'প্রথম সপ্তাহের শেষ, তাপমাত্রা ৮৭-৮৯°F এ নামান']
  },
  // Week 2: Days 8-14
  {
    day: 8,
    week: 2,
    feedDailyGm: 11,
    feedCumGm: 60,
    bodyWeightGm: 73,
    fcrStd: 0.82,
    tempFMin: 86,
    tempFMax: 88,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Remove newspaper entirely, chicks stay on fresh wood shavings', 'Increase brooding ring diameter'],
    tasksBn: ['মেঝের কাগজ তুলে ফেলুন, বাচ্চারা শুকনো তুষের ওপর থাকবে', 'ব্রুডিং বৃত্তের পরিধি বড় করুন']
  },
  {
    day: 9,
    week: 2,
    feedDailyGm: 12,
    feedCumGm: 72,
    bodyWeightGm: 80,
    fcrStd: 0.90,
    tempFMin: 86,
    tempFMax: 88,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Introduce hanging tubular feeders', 'Check for pasted vents'],
    tasksBn: ['ঝুলন্ত ফিডারে অল্প খাবার দেওয়া শুরু করুন', 'বাচ্চার পাছায় পায়খানা আটকে আছে কিনা লক্ষ্য করুন']
  },
  {
    day: 10,
    week: 2,
    feedDailyGm: 13,
    feedCumGm: 85,
    bodyWeightGm: 87,
    fcrStd: 0.98,
    tempFMin: 85,
    tempFMax: 87,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Gumboro vaccine preparation for Day 11-12', 'Clean all drinker trays with brush'],
    tasksBn: ['১১-১২ দিনের গামবোরো ভ্যাকসিনের পূর্বপ্রস্তুতি নিন', 'পানির পাত্র ব্রাশ দিয়ে ঘষে পরিষ্কার করুন']
  },
  {
    day: 11,
    week: 2,
    feedDailyGm: 14,
    feedCumGm: 99,
    bodyWeightGm: 94,
    fcrStd: 1.05,
    tempFMin: 85,
    tempFMax: 87,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Gumboro (IBD) 1st dose eye drop vaccination', 'Keep cool environment during vaccine'],
    tasksBn: ['গামবোরো (আইবিডি) ১ম ডোজ চোখের ড্রপ দিন', 'ভ্যাকসিন দেওয়ার সময় ঠান্ডা আবহাওয়া রাখুন'],
    isCritical: true
  },
  {
    day: 12,
    week: 2,
    feedDailyGm: 15,
    feedCumGm: 114,
    bodyWeightGm: 102,
    fcrStd: 1.12,
    tempFMin: 84,
    tempFMax: 86,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect vaccine response', 'Provide multivitamin in water'],
    tasksBn: ['টিকার পরের প্রতিক্রিয়া লক্ষ্য করুন', 'পানিতে মাল্টিভিটামিন সরবরাহ করুন']
  },
  {
    day: 13,
    week: 2,
    feedDailyGm: 16,
    feedCumGm: 130,
    bodyWeightGm: 110,
    fcrStd: 1.18,
    tempFMin: 84,
    tempFMax: 86,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Rake litter to avoid wet caking', 'Maintain natural cross-ventilation'],
    tasksBn: ['লিটার আলতো করে নেড়ে দিন যেন জমাট না বাধে', 'প্রাকৃতিক বাতাস চলাচলের ব্যবস্থা করুন']
  },
  {
    day: 14,
    week: 2,
    feedDailyGm: 17,
    feedCumGm: 147,
    bodyWeightGm: 118,
    fcrStd: 1.25,
    tempFMin: 83,
    tempFMax: 85,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['14-Day sample weighing (target 110-120g)', 'Week 2 milestone review'],
    tasksBn: ['১৪তম দিনে স্যাম্পল ওজন নিন (টার্গেট ১১০-১২০ গ্রাম)', '২য় সপ্তাহের কাজের মূল্যায়ন সম্পন্ন করুন']
  },
  // Week 3: Days 15-21
  {
    day: 15,
    week: 3,
    feedDailyGm: 18,
    feedCumGm: 165,
    bodyWeightGm: 127,
    fcrStd: 1.30,
    tempFMin: 82,
    tempFMax: 84,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Adjust feeder heights to bird back level', 'Gradually remove brooding guards'],
    tasksBn: ['ফিডারের উচ্চতা মুরগির পিঠের সমতায় রাখুন', 'ব্রুডিং চিকগার্ড সরিয়ে পুরো ঘরে ছেড়ে দিন']
  },
  {
    day: 16,
    week: 3,
    feedDailyGm: 19,
    feedCumGm: 184,
    bodyWeightGm: 137,
    fcrStd: 1.34,
    tempFMin: 82,
    tempFMax: 84,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect droppings for coccidiosis signs (blood or brown mucus)', 'Keep dry litter'],
    tasksBn: ['পায়খানায় রক্ত বা কক্সিডিওসিস এর লক্ষণ আছে কিনা পরীক্ষা করুন', 'লিটার সম্পূর্ণ শুকনো রাখুন']
  },
  {
    day: 17,
    week: 3,
    feedDailyGm: 20,
    feedCumGm: 204,
    bodyWeightGm: 147,
    fcrStd: 1.39,
    tempFMin: 81,
    tempFMax: 83,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Prepare for Gumboro booster vaccination at Day 18-19', 'Withhold water for 1.5 hours before vaccine'],
    tasksBn: ['১৮-১৯ দিনের গামবোরো বুস্টার টিকার প্রস্তুতি নিন', 'টিকা দেওয়ার ১.৫ ঘণ্টা আগে পানি সরিয়ে পিপাসা তৈরি করুন']
  },
  {
    day: 18,
    week: 3,
    feedDailyGm: 21,
    feedCumGm: 225,
    bodyWeightGm: 158,
    fcrStd: 1.42,
    tempFMin: 81,
    tempFMax: 83,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Gumboro (IBD) booster dose in drinking water with skimmed milk powder', 'Consume within 2 hours'],
    tasksBn: ['গামবোরো বুস্টার ডোজ পানিতে স্কিম মিল্ক পাউডার মিশিয়ে খাওয়ান', '২ ঘণ্টার মধ্যে টিকা মেশানো পানি শেষ করতে হবে'],
    isCritical: true
  },
  {
    day: 19,
    week: 3,
    feedDailyGm: 22,
    feedCumGm: 247,
    bodyWeightGm: 169,
    fcrStd: 1.46,
    tempFMin: 80,
    tempFMax: 82,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Offer fresh clean water after vaccine', 'Check flock appetite and vigor'],
    tasksBn: ['টিকার পর পরিষ্কার সুপেয় পানি দিন', 'বাচ্চাদের খাবারের আগ্রহ ও চঞ্চলতা পরীক্ষা করুন']
  },
  {
    day: 20,
    week: 3,
    feedDailyGm: 24,
    feedCumGm: 271,
    bodyWeightGm: 181,
    fcrStd: 1.50,
    tempFMin: 80,
    tempFMax: 82,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Ensure adequate feeder and drinker spaces (30 birds per feeder)', 'Control ammonia odor'],
    tasksBn: ['পর্যাপ্ত ফিডার ও ওয়াটারার নিশ্চিত করুন (প্রতি ফিডারে ৩০টি)', 'অ্যামোনিয়া গ্যাস জমতে দেবেন না']
  },
  {
    day: 21,
    week: 3,
    feedDailyGm: 26,
    feedCumGm: 297,
    bodyWeightGm: 193,
    fcrStd: 1.54,
    tempFMin: 79,
    tempFMax: 81,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['21-Day sample weight check (target 180-200g)', 'Prepare transition from starter to grower feed'],
    tasksBn: ['২১তম দিনে স্যাম্পল ওজন নিন (টার্গেট ১৮০-২০০ গ্রাম)', 'স্টার্টার থেকে গ্রোয়ার ফিডে পরিবর্তনের প্রস্তুতি নিন']
  },
  // Week 4: Days 22-28
  {
    day: 22,
    week: 4,
    feedDailyGm: 27,
    feedCumGm: 324,
    bodyWeightGm: 206,
    fcrStd: 1.57,
    tempFMin: 78,
    tempFMax: 80,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Start feed transition (75% starter + 25% grower)', 'Check room temperature'],
    tasksBn: ['খাবার পরিবর্তন শুরু (৭৫% স্টার্টার + ২৫% গ্রোয়ার)', 'ঘরের তাপমাত্রা ৭৮-৮০°F এ রাখুন']
  },
  {
    day: 23,
    week: 4,
    feedDailyGm: 29,
    feedCumGm: 353,
    bodyWeightGm: 220,
    fcrStd: 1.60,
    tempFMin: 78,
    tempFMax: 80,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Feed transition day 2 (50% starter + 50% grower)', 'BCRDV booster preparation'],
    tasksBn: ['খাবার পরিবর্তন ২য় দিন (৫০% স্টার্টার + ৫০% গ্রোয়ার)', 'বিসিআরডিভি বুস্টার টিকার প্রস্তুতি']
  },
  {
    day: 24,
    week: 4,
    feedDailyGm: 31,
    feedCumGm: 384,
    bodyWeightGm: 235,
    fcrStd: 1.63,
    tempFMin: 77,
    tempFMax: 79,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['BCRDV (Ranikhet) 2nd dose eye drop or drinking water', 'Maintain calm flock conditions'],
    tasksBn: ['বিসিআরডিভি (রাণীক্ষেত) ২য় ডোজ চোখের ড্রপ বা পানিতে দিন', 'খামারে শান্ত পরিবেশ রাখুন'],
    isCritical: true
  },
  {
    day: 25,
    week: 4,
    feedDailyGm: 33,
    feedCumGm: 417,
    bodyWeightGm: 250,
    fcrStd: 1.67,
    tempFMin: 76,
    tempFMax: 78,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Full grower feed adaptation', 'Inspect feather growth and uniform sizing'],
    tasksBn: ['সম্পূর্ণ গ্রোয়ার ফিডে স্থানান্তর করুন', 'পাখার বৃদ্ধি ও মুরগির সমসত্ত্বতা (Uniformity) দেখুন']
  },
  {
    day: 26,
    week: 4,
    feedDailyGm: 35,
    feedCumGm: 452,
    bodyWeightGm: 266,
    fcrStd: 1.70,
    tempFMin: 75,
    tempFMax: 77,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Provide liver tonic in water for digestion support', 'Adjust drinker height'],
    tasksBn: ['হজমশক্তি বাড়াতে পানিতে লিভার টনিক দিন', 'পানির পাত্র মুরগির পিঠ বরাবর উঁচুতে তুলুন']
  },
  {
    day: 27,
    week: 4,
    feedDailyGm: 37,
    feedCumGm: 489,
    bodyWeightGm: 283,
    fcrStd: 1.73,
    tempFMin: 75,
    tempFMax: 77,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Stir wet litter patches', 'Prepare for Fowl Pox vaccine at 28-30 days'],
    tasksBn: ['ভেজা লিটার সরিয়ে শুষ্ক তুষ যোগ করুন', '২৮-৩০ দিনের ফাউল পক্স (বসন্ত) ভ্যাকসিনের প্রস্তুতি নিন']
  },
  {
    day: 28,
    week: 4,
    feedDailyGm: 39,
    feedCumGm: 528,
    bodyWeightGm: 300,
    fcrStd: 1.76,
    tempFMin: 74,
    tempFMax: 76,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['28-Day weight audit (target 290-310g)', '4th week completion check'],
    tasksBn: ['২৮তম দিনে স্যাম্পল ওজন নিন (টার্গেট ২৯০-৩১০ গ্রাম)', '৪র্থ সপ্তাহের কাজের খতিয়ান সম্পন্ন করুন']
  },
  // Week 5: Days 29-35
  {
    day: 29,
    week: 5,
    feedDailyGm: 41,
    feedCumGm: 569,
    bodyWeightGm: 318,
    fcrStd: 1.79,
    tempFMin: 72,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Fowl Pox (বসন্ত) wing web puncture vaccination', 'Verify take reaction after 7 days'],
    tasksBn: ['ফাউল পক্স (বসন্ত) ডানার পর্দায় সুঁই ফুটিয়ে টিকা দিন', '৭ দিন পর টিকার প্রতিক্রিয়া (Take) পরীক্ষা করুন'],
    isCritical: true
  },
  {
    day: 30,
    week: 5,
    feedDailyGm: 43,
    feedCumGm: 612,
    bodyWeightGm: 337,
    fcrStd: 1.82,
    tempFMin: 72,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Clean feeders thoroughly', 'Ensure proper spacing (1.2 sq ft per Sonali bird)'],
    tasksBn: ['ফিডার ভালোভাবে পরিষ্কার করুন', 'পর্যাপ্ত জায়গা নিশ্চিত করুন (প্রতি সোনালীতে ১.২ বর্গফুট)']
  },
  {
    day: 31,
    week: 5,
    feedDailyGm: 44,
    feedCumGm: 656,
    bodyWeightGm: 357,
    fcrStd: 1.84,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Provide electrolyte during warm afternoon', 'Inspect litter condition'],
    tasksBn: ['দুপুরে গরম বেশি হলে পানিতে ইলেক্ট্রোলাইট দিন', 'ঘরের লিটারের অবস্থা পর্যবেক্ষণ করুন']
  },
  {
    day: 32,
    week: 5,
    feedDailyGm: 46,
    feedCumGm: 702,
    bodyWeightGm: 377,
    fcrStd: 1.86,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect flock activity and uniform feed consumption', 'Dust ventilation nets'],
    tasksBn: ['সব মুরগি সমানভাবে খাবার খাচ্ছে কিনা দেখুন', 'বাতাস চলাচলের জাল থেকে ধুলোবালি ঝেড়ে ফেলুন']
  },
  {
    day: 33,
    week: 5,
    feedDailyGm: 47,
    feedCumGm: 749,
    bodyWeightGm: 398,
    fcrStd: 1.88,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Check for any respiratory sounds during night silence', 'Ensure dry bedding'],
    tasksBn: ['রাতে নীরব পরিবেশে কোনো ঘড়ঘড় শব্দ বা সর্দি আছে কিনা শুনুন', 'শুষ্ক বিছানা বজায় রাখুন']
  },
  {
    day: 34,
    week: 5,
    feedDailyGm: 48,
    feedCumGm: 797,
    bodyWeightGm: 420,
    fcrStd: 1.90,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Provide calcium & vitamin D3 for bone strength', 'Clean water pipeline'],
    tasksBn: ['হাড়ের গঠন শক্ত রাখতে পানিতে ক্যালসিয়াম ও ভিটামিন ডি৩ দিন', 'পানির পাইপলাইন ফ্লাশ করুন']
  },
  {
    day: 35,
    week: 5,
    feedDailyGm: 50,
    feedCumGm: 847,
    bodyWeightGm: 442,
    fcrStd: 1.92,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['35-Day sample weight check (target 430-460g)', 'Deworming schedule consultation with vet'],
    tasksBn: ['৩৫তম দিনে স্যাম্পল ওজন নিন (টার্গেট ৪৩০-৪৬০ গ্রাম)', 'ভেটেরিনারি ডাক্তারের পরামর্শ অনুযায়ী কৃমিনাশকের প্রস্তুতি নিন']
  },
  // Week 6: Days 36-42
  {
    day: 36,
    week: 6,
    feedDailyGm: 51,
    feedCumGm: 898,
    bodyWeightGm: 465,
    fcrStd: 1.93,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Deworming medicine in drinking water if advised by vet', 'Do not deworm weak birds'],
    tasksBn: ['ডাক্তারের পরামর্শে সকালের পানিতে কৃমিনাশক ঔষধ দিন', 'অসুস্থ পাখিকে কৃমির ঔষধ দেওয়া নিষেধ'],
    isCritical: true
  },
  {
    day: 37,
    week: 6,
    feedDailyGm: 52,
    feedCumGm: 950,
    bodyWeightGm: 488,
    fcrStd: 1.95,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Provide Vitamin-B Complex and liver tonic post deworming', 'Rake litter thoroughly'],
    tasksBn: ['কৃমিনাশকের পরদিন ভিটামিন বি-কমপ্লেক্স ও লিভার টনিক দিন', 'লিটার ভালোভাবে উল্টেপাল্টে দিন']
  },
  {
    day: 38,
    week: 6,
    feedDailyGm: 53,
    feedCumGm: 1003,
    bodyWeightGm: 512,
    fcrStd: 1.96,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect droppings after deworming', 'Ensure pure fresh drinking water'],
    tasksBn: ['কৃমিনাশকের পর মলমূত্র পর্যবেক্ষণ করুন', 'সর্বদা নির্মল পানি নিশ্চিত রাখুন']
  },
  {
    day: 39,
    week: 6,
    feedDailyGm: 55,
    feedCumGm: 1058,
    bodyWeightGm: 536,
    fcrStd: 1.97,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Check bird mobility and leg vigor', 'Maintain optimal lighting schedule'],
    tasksBn: ['মুরগির চঞ্চলতা ও পায়ের শক্তি দেখুন', 'সঠিক আলোকসূচি বজায় রাখুন']
  },
  {
    day: 40,
    week: 6,
    feedDailyGm: 56,
    feedCumGm: 1114,
    bodyWeightGm: 561,
    fcrStd: 1.99,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['RDV (Ranikhet Adult Vaccine - Komarov strain) booster preparation', 'Inspect biosecurity'],
    tasksBn: ['আরডিভি (বড় রাণীক্ষেত ভ্যাকসিন) বুস্টারের প্রস্তুতি নিন', 'খামারের জৈব নিরাপত্তা বজায় রাখুন']
  },
  {
    day: 41,
    week: 6,
    feedDailyGm: 57,
    feedCumGm: 1171,
    bodyWeightGm: 586,
    fcrStd: 2.00,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['RDV booster (0.5 ml intramuscular injection in thigh or breast muscle)', 'Handle birds gently'],
    tasksBn: ['আরডিভি ভ্যাকসিন ০.৫ মিলি রানের মাংসে পুশ করুন', 'পাখি ধরার সময় শান্ত থাকুন'],
    isCritical: true
  },
  {
    day: 42,
    week: 6,
    feedDailyGm: 58,
    feedCumGm: 1229,
    bodyWeightGm: 612,
    fcrStd: 2.01,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['42-Day sample weight check (target 590-630g)', '6th week completion audit'],
    tasksBn: ['৪২তম দিনে স্যাম্পল ওজন নিন (টার্গেট ৫৯০-৬৩০ গ্রাম)', '৬ষ্ঠ সপ্তাহের অগ্রগতি পর্যালোচনা করুন']
  },
  // Week 7: Days 43-49
  {
    day: 43,
    week: 7,
    feedDailyGm: 60,
    feedCumGm: 1289,
    bodyWeightGm: 638,
    fcrStd: 2.02,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Provide multivitamin + mineral premix in feed/water', 'Inspect flock density'],
    tasksBn: ['খাবার বা পানিতে খনিজ লবণ ও মাল্টিভিটামিন দিন', 'ঘরে পর্যাপ্ত জায়গা আছে কিনা দেখুন']
  },
  {
    day: 44,
    week: 7,
    feedDailyGm: 61,
    feedCumGm: 1350,
    bodyWeightGm: 665,
    fcrStd: 2.03,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Check feeder distribution to ensure all birds feed uniformly', 'Control rodents/wild birds'],
    tasksBn: ['সব পাখি সমান খাবার পাচ্ছে কিনা ফিডার পুনর্বিন্যাস করুন', 'ইঁদুর ও বুনো পাখি নিয়ন্ত্রণ করুন']
  },
  {
    day: 45,
    week: 7,
    feedDailyGm: 62,
    feedCumGm: 1412,
    bodyWeightGm: 692,
    fcrStd: 2.04,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Start transition to Sonali Finisher feed if available', 'Monitor weekly FCR'],
    tasksBn: ['সোনালী ফিনিশার ফিডে রূপান্তর শুরু করুন', 'সাপ্তাহিক এফসিআর যাচাই করুন']
  },
  {
    day: 46,
    week: 7,
    feedDailyGm: 64,
    feedCumGm: 1476,
    bodyWeightGm: 720,
    fcrStd: 2.05,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Ensure abundant fresh air circulation', 'Clean drinker bases daily'],
    tasksBn: ['ঘরের ভেতর পর্যাপ্ত বিশুদ্ধ বাতাস নিশ্চিত করুন', 'প্রতিদিন পানির পাত্রের গোড়া পরিষ্কার করুন']
  },
  {
    day: 47,
    week: 7,
    feedDailyGm: 65,
    feedCumGm: 1541,
    bodyWeightGm: 748,
    fcrStd: 2.06,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Monitor feed consumption rate daily', 'Prevent feed wastage from excessive feeder swinging'],
    tasksBn: ['প্রতিদিনের খাদ্য গ্রহণের হার নথিবদ্ধ করুন', 'ফিডার অতিরিক্ত দুলে খাবার যেন না পড়ে']
  },
  {
    day: 48,
    week: 7,
    feedDailyGm: 66,
    feedCumGm: 1607,
    bodyWeightGm: 777,
    fcrStd: 2.07,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect flock uniform weight distribution', 'Observe bird comb color and brightness'],
    tasksBn: ['মুরগির সমরূপ ওজন ও ঝাঁকের স্বাস্থ্য পরীক্ষা করুন', 'ঝুঁটির লালচে উজ্জ্বল রঙ পর্যবেক্ষণ করুন']
  },
  {
    day: 49,
    week: 7,
    feedDailyGm: 67,
    feedCumGm: 1674,
    bodyWeightGm: 806,
    fcrStd: 2.08,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['49-Day sample weight check (target 780-830g)', '7th week audit completed'],
    tasksBn: ['৪৯তম দিনে স্যাম্পল ওজন নিন (টার্গেট ৭৮০-৮৩০ গ্রাম)', '৭ম সপ্তাহের কাজের অগ্রগতি লিপিবদ্ধ করুন']
  },
  // Week 8: Days 50-56
  {
    day: 50,
    week: 8,
    feedDailyGm: 68,
    feedCumGm: 1742,
    bodyWeightGm: 836,
    fcrStd: 2.08,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Monitor market rates and communicate with buyers/wholesalers', 'Check flock appetite'],
    tasksBn: ['বাজার দর পর্যবেক্ষণ করুন ও পাইকারদের সাথে যোগাযোগ শুরু করুন', 'খাবারের চাহিদা পর্যবেক্ষণ করুন']
  },
  {
    day: 51,
    week: 8,
    feedDailyGm: 69,
    feedCumGm: 1811,
    bodyWeightGm: 866,
    fcrStd: 2.09,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Keep feeding schedule strictly on time (morning and afternoon)', 'Avoid midday stress'],
    tasksBn: ['খাবার দেওয়ার সময়সূচি বজায় রাখুন (সকাল ও বিকাল)', 'দুপুরে কোনো উত্তেজনা সৃষ্টি করবেন না']
  },
  {
    day: 52,
    week: 8,
    feedDailyGm: 70,
    feedCumGm: 1881,
    bodyWeightGm: 897,
    fcrStd: 2.10,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Fowl Cholera vaccine preparation if recommended locally', 'Maintain pure drinking water'],
    tasksBn: ['ফাউল কলেরা ভ্যাকসিনের প্রয়োজনীয়তা যাচাই করুন', 'বিশুদ্ধ পানি সবসময় প্রস্তুত রাখুন']
  },
  {
    day: 53,
    week: 8,
    feedDailyGm: 71,
    feedCumGm: 1952,
    bodyWeightGm: 928,
    fcrStd: 2.10,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Inspect birds for any respiratory symptoms', 'Ensure clean feeding troughs'],
    tasksBn: ['কোনো মুরগির সর্দি বা কাশি আছে কিনা লক্ষ্য করুন', 'খাবারের পাত্র সবসময় পরিচ্ছন্ন রাখুন']
  },
  {
    day: 54,
    week: 8,
    feedDailyGm: 72,
    feedCumGm: 2024,
    bodyWeightGm: 960,
    fcrStd: 2.11,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Flock sorting: separate underweight birds for special feeding care', 'Check litter dryness'],
    tasksBn: ['ছোট মুরগিগুলোকে আলাদা করে বিশেষ যত্নের ব্যবস্থা করুন', 'লিটার শুষ্ক রাখুন']
  },
  {
    day: 55,
    week: 8,
    feedDailyGm: 73,
    feedCumGm: 2097,
    bodyWeightGm: 992,
    fcrStd: 2.11,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Maintain calm environment', 'Calculate current batch feed cost and projected revenue'],
    tasksBn: ['খামারে শান্ত পরিবেশ রাখুন', 'চলতি ব্যাচের মোট খাদ্য খরচ ও সম্ভাব্য বিক্রয়মূল্য হিসাব করুন']
  },
  {
    day: 56,
    week: 8,
    feedDailyGm: 74,
    feedCumGm: 2171,
    bodyWeightGm: 1025,
    fcrStd: 2.12,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['56-Day sample weight check (target 980-1050g)', 'Sonali 1kg commercial milestone reached!'],
    tasksBn: ['৫৬তম দিনে স্যাম্পল ওজন নিন (টার্গেট ৯৮০-১০৫০ গ্রাম)', 'সোনালী মুরগির ১ কেজি বাণিজ্যিক মাইলফলক অর্জিত!'],
    isCritical: true
  },
  // Week 9: Days 57-60 (Marketing Phase)
  {
    day: 57,
    week: 9,
    feedDailyGm: 74,
    feedCumGm: 2245,
    bodyWeightGm: 1058,
    fcrStd: 2.12,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Marketing readiness: verify batch health records', 'Zero antibiotic withdrawal period compliance'],
    tasksBn: ['বিক্রয়ের প্রস্তুতি: স্বাস্থ্য রেকর্ড যাচাই করুন', 'অ্যান্টিবায়োটিকের উইথড্রয়াল পিরিয়ড নিশ্চিত করুন']
  },
  {
    day: 58,
    week: 9,
    feedDailyGm: 75,
    feedCumGm: 2320,
    bodyWeightGm: 1092,
    fcrStd: 2.12,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Confirm buyer pickup time', 'Prepare transport crates and weighing scales'],
    tasksBn: ['পাইকারের গাড়ি আসার সময় নিশ্চিত করুন', 'মুরগি তোলার খাঁচা ও ডিজিটাল স্কেল প্রস্তুত রাখুন']
  },
  {
    day: 59,
    week: 9,
    feedDailyGm: 75,
    feedCumGm: 2395,
    bodyWeightGm: 1126,
    fcrStd: 2.13,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Withhold feed 4-6 hours prior to weighing/sale', 'Keep abundant drinking water until catch'],
    tasksBn: ['বিক্রির ৪-৬ ঘণ্টা আগে খাবার বন্ধ করুন', 'পাখি ধরার আগ পর্যন্ত প্রচুর বিশুদ্ধ পানি চালু রাখুন']
  },
  {
    day: 60,
    week: 9,
    feedDailyGm: 75,
    feedCumGm: 2470,
    bodyWeightGm: 1160,
    fcrStd: 2.13,
    tempFMin: 70,
    tempFMax: 75,
    relHumidityMin: 60,
    relHumidityMax: 70,
    tasks: ['Final flock harvest and weighing', 'Complete batch sales and finalize settlement report'],
    tasksBn: ['চুড়ান্ত মুরগি বিক্রয় ও ওজন গ্রহণ', 'বিক্রির হিসাব এন্ট্রি দিয়ে ব্যাচ সম্পূর্ণ ও লাভ-ক্ষতির চূড়ান্ত হিসাব করুন'],
    isCritical: true
  }
];

export function getSonaliSopForDay(day: number): DailySopItem {
  const bounded = Math.max(1, Math.min(60, Math.round(day)));
  const found = SONALI_SOP_SCHEDULE.find(s => s.day === bounded);
  if (found) return found;
  return SONALI_SOP_SCHEDULE[SONALI_SOP_SCHEDULE.length - 1];
}
